### ISSUE TITLE
SQS submit timer does not name the queue

### ISSUE THREAD

**Issue by seb-cr** [comicrelief/lambda-wrapper#76]
The SQS service times sending messages and logs a message like `sqs-send-message-<UUID> took 40ms`.

In services where messages are sent to several queues at once (e.g. giftaid submit) the current log messages are insufficient when something goes wrong, e.g. if one send times out. Also, the UUID is randomly generated just for the timer, but in this context looks like it should be a message ID, which is misleading.

Suggesting using a clearer message like `SQS - sending message to <name> took 40ms`.

**Comment by dipasqualew** [comment]
I came here to open the same issue. I think I am going to implement this today I believe it's quite important to see the full qualified queue url for logging purposes.
